spring:

  application:
    name: ${APPLICATION:sba}

  config:
    import:
      - optional:classpath:application-common.yaml
      - 'optional:kubernetes:'

  cloud:
    kubernetes:
      reload:
        enabled: true
      client:
        namespace: ${NAMESPACE}
      config:
        enabled: true
        namespace: ${NAMESPACE}
        name: ${spring.application.name}
      discovery:
        enabled: true
        namespaces:
          - ${NAMESPACE}
        service-labels:
          framework: spring-boot

logging:
  level:
    io.kubernetes.client.informer.cache.ReflectorRunnable: warn
