server:
  port: ${SERVER_PORT:80}

spring:

  output:
    ansi:
      enabled: always

  threads:
    virtual:
      enabled: true

  boot:
    admin:
      client:
        url: ${SBA_CLIENT_URL:http://sba}
        enabled: ${SBA_CLIENT_ENABLED:false}

management:
  info:
    os:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    access:
      default: read_only
  endpoint:
    startup:
      access: read_only
    shutdown:
      access: read_only
    env:
      show-values: always
      access: read_only
    configprops:
      show-values: always
      access: read_only
    health:
      probes:
        enabled: true
        add-additional-paths: true
      show-components: always
      show-details: always
      group:
        readiness:
          include: "*"
        liveness:
          include: "*"
      access: read_only
    logfile:
      external-file: /logs/${spring.application.name}/${HOSTNAME:HOSTNAME}.log
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

  observations:
    key-values:
      service.name: ${spring.application.name}
      service.namespace: ${NAMESPACE:zero}
      application: ${spring.application.name}
      namespace: ${NAMESPACE:zero}
      hostname: ${HOSTNAME:HOSTNAME}
      instance: ${HOSTNAME:None}

    annotations:
      enabled: true
    r2dbc:
      include-parameter-values: true

  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: W3C

  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
      service.namespace: ${NAMESPACE:zero}
      application: ${spring.application.name}
      namespace: ${NAMESPACE:zero}
      hostname: ${HOSTNAME:HOSTNAME}
      instance: ${HOSTNAME:None}

  otlp:

    metrics:
      export:
        url: ${OTLP_METRICS_ENDPOINT:http://otel-collector:4318/v1/metrics}
        enabled: ${OTLP_METRICS_ENABLED:true}

    tracing:
      endpoint: ${OTLP_TRACING_ENDPOINT:http://otel-collector:4318/v1/traces}
      export:
        enabled: ${OTLP_TRACING_ENABLED:true}

    logging:
      endpoint: ${OTLP_LOGGING_ENDPOINT:http://otel-collector:4318/v1/logs}
      export:
        enabled: ${OTLP_LOGGING_ENABLED:true}

otel:
  sdk:
    disabled: false
  exporter:
    otlp:
      endpoint: ${OTLP_ENDPOINT:http://otel-collector:4318/}

logging:
  level:
    root: info
    web: info
    sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.jdbc.core.StatementCreatorUtils: trace
  file:
    name: /logs/${spring.application.name}/${HOSTNAME:HOSTNAME}.log
  logback:
    rollingpolicy:
      file-name-pattern: /logs/${spring.application.name}/%d{yyyy-MM-dd}/${HOSTNAME:-${spring.application.name}}.log.%d{yyyy-MM-dd}.%i.gz
      clean-history-on-start: false
      max-file-size: 100MB
      total-size-cap: 10GB
      max-history: 30

springdoc:
  group-configs:
    - group: default
      paths-to-match: /api/**

knife4j:
  # 临时关闭增强特性，等待作者修复 4.5.0 中引用的 springdoc 版本过低与 spring-boot 3.4.x 不兼容的问题
  enable: false

zero:
  aes-key: ${AES_KEY:0000000000000000}
  aes-iv: ${AES_IV:0000000000000000}
  service:
    zero:
      demo: ${ZERO_SERVICE_DEMO:demo.zero}
      base: ${ZERO_SERVICE_BASE:base.zero}
      auth: ${ZERO_SERVICE_AUTH:auth.zero}
