spring:

  application:
    name: ${APPLICATION:auth}

  config:
    import:
      - optional:classpath:application-common.yaml
      - optional:classpath:application-mysql.yaml
      - optional:classpath:application-redis.yaml

  data:
    redis:
      database: ${REDIS_DATABASE:14}

  security:
    oauth2:

      authorizationserver:
        client:
          zero:
            registration:
              client-id: ${ZERO_OAUTH2_CLIENT_ID:zero}
              client-secret: ${ZERO_OAUTH2_CLIENT_SECRET:{noop}zero}
              client-name: ${ZERO_OAUTH2_CLIENT_NAME:zero}
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
                - "client_secret_jwt"
                - "private_key_jwt"
                - "none"
                - "tls_client_auth"
                - "self_signed_tls_client_auth"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
                - "password"
                - "urn:ietf:params:oauth:grant-type:jwt-bearer"
                - "urn:ietf:params:oauth:grant-type:device_code"
                - "urn:ietf:params:oauth:grant-type:token-exchange"
                - "id"
              redirect-uris:
                - "http://auth.zero/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://auth.zero/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
            token:
              access-token-format: ${ZERO_OAUTH2_ACCESS_TOKEN_FORMAT:reference}
              access-token-time-to-live: ${ZERO_OAUTH2_ACCESS_TOKEN_TIME_TO_LIVE:P7D}
              refresh-token-time-to-live: ${ZERO_OAUTH2_REFRESH_TOKEN_TIME_TO_LIVE:P30D}

      resourceserver:
        opaque-token:
          client-id: ${ZERO_OAUTH2_CLIENT_ID:zero}
          client-secret: ${ZERO_OAUTH2_CLIENT_SECRET:zero}
          introspection-uri: ${ZERO_OAUTH2_INTROSPECTION_URI:http://auth.zero/oauth2/introspect}
